version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    command: uvicorn backend.app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8008:8000"
    env_file:
      - backend/.env
    networks:
      - backend
    # tty: true
  # app:
  #   container_name: app
  #   image: app
  #   # environment:
  #   #   - MONGODB_URL=mongodb://mongodb/test_database
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - backend

  # mongo_db:
  #   image: mongo
  #   container_name: "mongo_db"
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - backend



networks:
  backend:
    driver: bridge