version: '3.7'
services:
  web:
    container_name: web
    image: nginx:alpine
    depends_on:
      - backend
    ports:
      - "8082:80"
    volumes:
      - ./app/backend/app/conf.d:/etc/nginx/conf.d
    networks:
      - custom
  
  backend:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "8000:8000"
    networks:
      - custom
    
  # mongo_db:
  #   image: mongo
  #   container_name: "mongo_db"
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - backend



networks:
  custom:
    driver: bridge